name: Deploy to Firebase Hosting (Dev and Prod)

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular
        run: |
          if [ "${GITHUB_REF##*/}" == "main" ]; then
            npm run build:prod
          else
            npm run build:dev
          fi

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ 
            github.ref == 'refs/heads/main' && secrets.FIREBASE_SERVICE_ACCOUNT_LIGHTHOUSEPROD_D5F45 || secrets.FIREBASE_SERVICE_ACCOUNT_LIGHTHOUSEDEV 
          }}
          channelId: live
          projectId: ${{ 
            github.ref == 'refs/heads/main' && 'lighthouseprod-d5f45' || 'lighthousedev-64439' 
          }}
          target: ${{ 
            github.ref == 'refs/heads/main' && 'prod' || 'dev' 
          }}