name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use the Node.js version your project requires

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Install Angular CLI globally (fixes 'ng not found')
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Build Angular project for production
      - name: Build Angular PROD
        run: ng build --configuration=production

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIGHTHOUSEPROD_D5F45 }}'
          channelId: live
          projectId: lighthouseprod-d5f45
